/* Boolean constants. */
boolean b     := false;
boolean not_b := true;

/* Char constants. */
char c  := 'c';
char hc := 0xFE;

/* Integer constants. */
int NULL := 0;
int i    := 254;

/* Floating point constants. */
float dot_started            :=   .314;
float zero_started           :=  0.314;
float non_zero_digit_started :=  3.314;
float big                    :=  31.3145;

/* String constants */
string hello := "Hello, World! How are you feeling today? Big string coming in!!!";
